radius: 10
me: "&7 * {player} : {message}"
do: "&f{message} ({player})"
try: "&7 * {player} : {message}"
b: "&7(( {player} : {message} ))"
changename_cost: 20000
tryes:
  - "&1\u041d\u0435\u0443\u0434\u0430\u0447\u043d\u043e"
  - "&f\u0423\u0434\u0430\u0447\u043d\u043e"